export const TOGGLE_LOGIN = "TOGGLE_LOGIN";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const RESET_SHARED_STATE = "RESET_SHARED_STATE";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
